FIX
File "/home/travis/build/eLBati/l10n-italy/l10n_it_fatturapa_in/wizard/__init__.py", line 2, in <module>
from . import wizard_import_fatturapa
File "/home/travis/build/eLBati/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 8, in <module>
from odoo.addons.l10n_it_fatturapa.bindings import fatturapa_v_1_2
File "/home/travis/build/eLBati/l10n-italy/l10n_it_fatturapa/bindings/fatturapa_v_1_2.py", line 30, in <module>
import _ds as _ImportedBinding__ds
ImportError: No module named '_ds'

and move to py3